version: "3.9"

services:
  app:
    image: event-service
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: document-db-aws
      SPRING_DATA_MONGODB_PORT: 27017